### ISSUE TITLE
The screen updates slowly when I adjust max_width to 0

### ISSUE THREAD

**Issue by KzDog** [razumeiko/py-android-viewer#3]
Hi, I reach this project from SCRCPY, it works well in my pc and your code is great.

But I had a little problem, when I adjust max_width to 0, the resolution changed to 1080*2160, and then the screen updates very slowly. If I only use the latest frame(Queue(maxsize=1)), the update speed is back to normal, but the screen is blurry.

So, could you give me some support? I'm looking forward to your reply soon.

**Comment by razumeiko** [comment]
Hi. I did not use full resolution, i'll test max_width=0 this week and will back to you.

**Comment by KzDog** [comment]
Hi, I'm still following this issue. Looking forward to your reply.

**Comment by razumeiko** [comment]
@KzDog sorry for the delay, busy days.
So i made some experiments and research and there is no an easy way to get the latest frame, it is requires more code to keep frames solid.

But i made some optimisation and remove Threading and Queue. Socket is non blocking now and instead one frame you will receive multiple frames (see example in README).
This increase stability and improve speed a little bit but with max_fps  set to 0 i still have the delay, the most consumed part here is `self.codec.decode(packet)` and with max_fps == 0 you will decode each frame ( it might be >60 frames per second).

If you are using it for some computer vision then max_fps set to 15-30 will be enough. I checked this code with `max_fps=30, max_width=0` and it works without any delays. And one more thing to keep in mind, speed will also depends on your PC and CPU.

**Comment by KzDog** [comment]
@razumeiko Thank you for your work. I'll try it.
It's going to be a great project! : )
