### ISSUE TITLE
CPU usage is too high

### ISSUE THREAD

**Issue by JiXiaoYao** [razumeiko/py-android-viewer#6]
When the program is running, the CPU usage is too high, and the I7 9750H occupies nearly 15% of the CPU.
Compared with the original program, scrcpy runs only 1%.

![image](https://user-images.githubusercontent.com/26181058/86524490-405dca80-be49-11ea-8f39-9dc611751976.png)

![image](https://user-images.githubusercontent.com/26181058/86524494-51a6d700-be49-11ea-896e-d8c93a688686.png)

**Comment by razumeiko** [comment]
By default it will use full size and bitrate, try to configure these values especially max_width. For example set it to 1024. Also you can decrease FPS if you don’t need frequent update, default is 30 frames per second. You can add delays or sleep and skip frames in queue and get only latest and try to optimize other parts of code. This is constructor and can be used for different needs.
And this is python and not c++ it will be slower than c++.

**Comment by JiXiaoYao** [comment]
emmmmm
I think I have solved this problem
After I made some changes to the network, the latency dropped, the FPS rose, and the most important thing was that the CPU usage also dropped.
I will send you a pull

**Comment by JiXiaoYao** [comment]
emmmmm
I think I have solved this problem
After I made some changes to the network, the CPU usage dropped.
I will send you a pull

**Comment by JiXiaoYao** [comment]
#7 Pull has been submitted

**Comment by razumeiko** [comment]
Hey, thanks for PR but if you will check commits you will notice that i changed blocking to nonblocking recently to increase speed. I think this config is depends on requirements of the project.
